name: ASP.NET Core CI

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Pack the nugets
      run: dotnet pack --configuration Release
#    - name: Publish the nugets
#      run: for i in `find | grep '.nupkg'`; do dotnet nuget push $i -k $NugetApiKey -s https://api.nuget.org/v3/index.json; done
